/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compila;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import java.util.stream.Stream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.stream.Collectors;
import java.io.IOException;

public class AppTest {

  App app;

  @Before
  public void setup() {
    app = new App();
  }
  
  public void doParserTest(int testfileNumber) throws IOException {

    String t = app.doRunParser(new String[] {
	"src/test/resources/parsing/test" + Integer.toString(testfileNumber) + ".cmp",
	"src/test/resources/parsing/test" + Integer.toString(testfileNumber) + ".ast"});

    assertEquals((Files.lines(Paths.get("src/test/resources/parsing/test" +
					Integer.toString(testfileNumber) + ".ast")))		     
		 .collect(Collectors.joining()),
		 (Files.lines(Paths.get("src/test/resources/parsing/test" +
					Integer.toString(testfileNumber) + ".expected")))
		 .collect(Collectors.joining()));  
  }

  public void parserFullProgramTest(String programname) {
    String t = app.doRunParser(new String [] {
	"src/test/resources/fullprograms/" + programname + ".cmp",
      "src/test/resources/fullprograms/" + programname + ".ast"});
  }

  @Test
  public void test1() throws IOException {
    doParserTest(1);
  }

  @Test
  public void test2() throws IOException {
    doParserTest(2);
  }

  @Test
  public void test3() throws IOException {
    doParserTest(3);
  }

  @Test
  public void test4() throws IOException {
    doParserTest(4);
  }

  @Test
  public void test5() throws IOException {
    doParserTest(5);
  }

  @Test
  public void test6() throws IOException {
    doParserTest(6);
  }

  @Test
  public void test7() throws IOException {
    doParserTest(7);
  }

  @Test
  public void test8() throws IOException {
    doParserTest(8);
  }
 
  @Test
  public void test9() throws IOException {
    doParserTest(9);
  }

  @Test
  public void complexAdditionParserTest() {
    parserFullProgramTest("complexaddition");
  }

  @Test
  public void euclidParserTest() {
    parserFullProgramTest("euclid");
  }

  @Test
  public void plogParserTest() {
    parserFullProgramTest("plog");
  }

  @Test
  public void runmeParserTest() {
    parserFullProgramTest("runme");
  }  
}


