
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ASSIGNMENT = 3;
  public static final int ASTERISK = 4;
  public static final int SLASH = 45;
  public static final int EQUALS = 17;
  public static final int GREATER = 21;
  public static final int INT = 25;
  public static final int REF = 40;
  public static final int LESS = 26;
  public static final int MINUS = 29;
  public static final int FLOATLITERAL = 52;
  public static final int CURLPARRIGHT = 11;
  public static final int SEMICOLON = 44;
  public static final int NOT = 31;
  public static final int AND = 2;
  public static final int LESSEQUAL = 27;
  public static final int IN = 24;
  public static final int OR = 34;
  public static final int BOOL = 6;
  public static final int COMMA = 9;
  public static final int FI = 19;
  public static final int BEGIN = 5;
  public static final int PLUS = 37;
  public static final int IF = 23;
  public static final int CARET = 7;
  public static final int DOT = 14;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int OD = 33;
  public static final int TRUE = 47;
  public static final int BOOLLITERAL = 51;
  public static final int PROGRAM = 39;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int CURLPARLEFT = 10;
  public static final int NULL = 32;
  public static final int LESSGREATER = 28;
  public static final int NAME = 54;
  public static final int PARRIGHT = 36;
  public static final int INTLITERAL = 53;
  public static final int GREATEREQUAL = 22;
  public static final int COLON = 8;
  public static final int ELSE = 15;
  public static final int WHILE = 49;
  public static final int PARLEFT = 35;
  public static final int FLOAT = 20;
  public static final int THEN = 46;
  public static final int END = 16;
  public static final int STRING = 42;
  public static final int STRINGLITERAL = 50;
  public static final int FALSE = 18;
  public static final int STRUCT = 43;
  public static final int VAR = 48;
  public static final int PROCEDURE = 38;
  public static final int DEREF = 12;
  public static final int DO = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "ASSIGNMENT",
  "ASTERISK",
  "BEGIN",
  "BOOL",
  "CARET",
  "COLON",
  "COMMA",
  "CURLPARLEFT",
  "CURLPARRIGHT",
  "DEREF",
  "DO",
  "DOT",
  "ELSE",
  "END",
  "EQUALS",
  "FALSE",
  "FI",
  "FLOAT",
  "GREATER",
  "GREATEREQUAL",
  "IF",
  "IN",
  "INT",
  "LESS",
  "LESSEQUAL",
  "LESSGREATER",
  "MINUS",
  "NEW",
  "NOT",
  "NULL",
  "OD",
  "OR",
  "PARLEFT",
  "PARRIGHT",
  "PLUS",
  "PROCEDURE",
  "PROGRAM",
  "REF",
  "RETURN",
  "STRING",
  "STRUCT",
  "SEMICOLON",
  "SLASH",
  "THEN",
  "TRUE",
  "VAR",
  "WHILE",
  "STRINGLITERAL",
  "BOOLLITERAL",
  "FLOATLITERAL",
  "INTLITERAL",
  "NAME"
  };
}

